"""Implementar indices compuestos y nuevos campos de configuracion

Revision ID: 00c39192aa8b
Revises: 86ff13a6c14b
Create Date: 2025-08-24 22:06:52.062464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '00c39192aa8b'
down_revision: Union[str, Sequence[str], None] = '86ff13a6c14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   #op.create_index(op.f('ix_articulos_codigo_interno'), 'articulos', ['codigo_interno'], unique=False)
   #op.create_unique_constraint('uq_codigo_interno_empresa', 'articulos', ['codigo_interno', 'id_empresa'])
   #op.add_column('configuracion_empresa', sa.Column('formato_comprobante_predeterminado', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
   #op.add_column('configuracion_empresa', sa.Column('limite_consumidor_final', sa.Float(), nullable=False))
   #op.create_index(op.f('ix_configuracion_empresa_cuit'), 'configuracion_empresa', ['cuit'], unique=True)
   #op.create_index(op.f('ix_empresas_cuit'), 'empresas', ['cuit'], unique=True)
   # op.create_index(op.f('ix_empresas_nombre_legal'), 'empresas', ['nombre_legal'], unique=True)
   # op.create_index(op.f('ix_terceros_cuit'), 'terceros', ['cuit'], unique=False)
    #op.create_unique_constraint('uq_cuit_empresa', 'terceros', ['cuit', 'id_empresa'])
    op.add_column('ventas', sa.Column('id_venta_lote_padre', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ventas_id_venta_lote_padre'), 'ventas', ['id_venta_lote_padre'], unique=False)
    op.create_foreign_key(None, 'ventas', 'ventas', ['id_venta_lote_padre'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ventas', type_='foreignkey')
    op.drop_index(op.f('ix_ventas_id_venta_lote_padre'), table_name='ventas')
    op.drop_column('ventas', 'id_venta_lote_padre')
    #op.drop_constraint('uq_cuit_empresa', 'terceros', type_='unique')
    #op.drop_index(op.f('ix_terceros_cuit'), table_name='terceros')
    #op.drop_index(op.f('ix_empresas_nombre_legal'), table_name='empresas')
    #op.drop_index(op.f('ix_empresas_cuit'), table_name='empresas')
    #op.drop_index(op.f('ix_configuracion_empresa_cuit'), table_name='configuracion_empresa')
    #op.drop_column('configuracion_empresa', 'limite_consumidor_final')
    #op.drop_column('configuracion_empresa', 'formato_comprobante_predeterminado')
    #op.drop_constraint('uq_codigo_interno_empresa', 'articulos', type_='unique')
    #op.drop_index(op.f('ix_articulos_codigo_interno'), table_name='articulos')
    # ### end Alembic commands ###
