"""Añadir campo de aclaraciones (definitivo)

Revision ID: 103d0b7a36c1
Revises: 00c39192aa8b
Create Date: 2025-08-25 00:28:24.539356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '103d0b7a36c1'
down_revision: Union[str, Sequence[str], None] = '00c39192aa8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion_empresa', sa.Column('aclaraciones_legales', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion_empresa', 'aclaraciones_legales')
    # ### end Alembic commands ###
