"""Agrego id_empresa a usuarios

Revision ID: 124393c8a320
Revises: d9fc284e1026
Create Date: 2025-07-25 17:21:40.554003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '124393c8a320'
down_revision: Union[str, Sequence[str], None] = 'd9fc284e1026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'articulos', 'empresas', ['id_empresa'], ['id'])
    #op.drop_column('articulos', 'codigo_proveedor')
    #op.drop_column('articulos', 'id_proveedor_principal')
    op.add_column('categorias', sa.Column('id_empresa', sa.Integer(), nullable=False))
    op.drop_index(op.f('nombre'), table_name='categorias')
    op.create_unique_constraint('uq_nombre_empresa_categoria', 'categorias', ['nombre', 'id_empresa'])
    op.create_foreign_key(None, 'categorias', 'empresas', ['id_empresa'], ['id'])
    op.add_column('marcas', sa.Column('id_empresa', sa.Integer(), nullable=False))
    op.drop_index(op.f('nombre'), table_name='marcas')
    op.create_unique_constraint('uq_nombre_empresa_categoria', 'marcas', ['nombre', 'id_empresa'])
    op.create_foreign_key(None, 'marcas', 'empresas', ['id_empresa'], ['id'])
    op.add_column('terceros', sa.Column('id_empresa', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'terceros', 'empresas', ['id_empresa'], ['id'])
    op.add_column('usuarios', sa.Column('id_empresa', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'usuarios', 'empresas', ['id_empresa'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'id_empresa')
    op.drop_constraint(None, 'terceros', type_='foreignkey')
    op.drop_column('terceros', 'id_empresa')
    op.drop_constraint(None, 'marcas', type_='foreignkey')
    op.drop_constraint('uq_nombre_empresa_categoria', 'marcas', type_='unique')
    op.create_index(op.f('nombre'), 'marcas', ['nombre'], unique=True)
    op.drop_column('marcas', 'id_empresa')
    op.drop_constraint(None, 'categorias', type_='foreignkey')
    op.drop_constraint('uq_nombre_empresa_categoria', 'categorias', type_='unique')
    op.create_index(op.f('nombre'), 'categorias', ['nombre'], unique=True)
    op.drop_column('categorias', 'id_empresa')
    op.add_column('articulos', sa.Column('id_proveedor_principal', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('articulos', sa.Column('codigo_proveedor', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'articulos', type_='foreignkey')
    # ### end Alembic commands ###
