"""Crear la tabla para LlaveMaestra

Revision ID: 1955211de63c
Revises: d49af62587b5
Create Date: 2025-07-19 15:19:31.866713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '1955211de63c'
down_revision: Union[str, Sequence[str], None] = 'd49af62587b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llave_maestra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llave', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llave_maestra_llave'), 'llave_maestra', ['llave'], unique=True)
   


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    # ### end Alembic commands ###
