"""Agregar columna a config empresa

Revision ID: 31bdd242626a
Revises: 62597ec87808
Create Date: 2025-08-05 10:43:42.770770

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31bdd242626a'
down_revision: Union[str, Sequence[str], None] = '62597ec87808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articulos', sa.Column('ubicacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('configuracion_empresa', sa.Column('cuit', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_configuracion_empresa_cuit'), 'configuracion_empresa', ['cuit'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuracion_empresa_cuit'), table_name='configuracion_empresa')
    op.drop_column('configuracion_empresa', 'cuit')
    op.drop_column('articulos', 'ubicacion')
    # ### end Alembic commands ###
