"""Agrega saldo_final_transferencias a caja_sesiones

Revision ID: 62597ec87808
Revises: acf4adcf5767
Create Date: 2025-08-04 17:52:34.001576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62597ec87808'
down_revision: Union[str, Sequence[str], None] = 'acf4adcf5767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caja_sesiones', sa.Column('saldo_final_transferecias', sa.Float(), nullable=True))
    op.add_column('caja_sesiones', sa.Column('saldo_final_bancario', sa.Float(), nullable=True))
    op.add_column('caja_sesiones', sa.Column('saldo_final_efectivo', sa.Float(), nullable=True))
    op.create_index(op.f('ix_terceros_cuit'), 'terceros', ['cuit'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terceros_cuit'), table_name='terceros')
    op.drop_column('caja_sesiones', 'saldo_final_efectivo')
    op.drop_column('caja_sesiones', 'saldo_final_bancario')
    op.drop_column('caja_sesiones', 'saldo_final_transferecias')
    # ### end Alembic commands ###
