"""cambiar default de empresa (colores y iconos)

Revision ID: 86ff13a6c14b
Revises: 31bdd242626a
Create Date: 2025-08-07 12:50:48.329717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '86ff13a6c14b'
down_revision: Union[str, Sequence[str], None] = '31bdd242626a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articulos', 'ubicacion',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
 
    # ### end Alembic commands ###
