"""Cambiar tipo de columna cuit a VARCHAR

Revision ID: 90d209d80239
Revises: e31a21837018
Create Date: 2025-07-16 23:26:13.754303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '90d209d80239'
down_revision: Union[str, Sequence[str], None] = 'e31a21837018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('terceros', 'cuit',
               existing_type=mysql.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('terceros', 'cuit',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
