"""Añadir columna tipo_comprobante_solicitado a Ventas

Revision ID: acf4adcf5767
Revises: bfb07d77a2fa
Create Date: 2025-08-01 18:49:56.537382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'acf4adcf5767'
down_revision: Union[str, Sequence[str], None] = 'bfb07d77a2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ventas', 'tipo_comprobante_solicitado',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_ventas_facturada'), 'ventas', ['facturada'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ventas_facturada'), table_name='ventas')
    op.alter_column('ventas', 'tipo_comprobante_solicitado',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
