"""Descripción de tu cambio

Revision ID: bfb07d77a2fa
Revises: 124393c8a320
Create Date: 2025-07-25 17:27:28.365686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb07d77a2fa'
down_revision: Union[str, Sequence[str], None] = '124393c8a320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'terceros', 'empresas', ['id_empresa'], ['id'])
    #op.add_column('usuarios', sa.Column('id_empresa', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'usuarios', 'empresas', ['id_empresa'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'id_empresa')
    op.drop_constraint(None, 'terceros', type_='foreignkey')
    # ### end Alembic commands ###
