"""Cambios de ticiano

Revision ID: d9fc284e1026
Revises: de235a2bc4ef
Create Date: 2025-07-25 16:36:58.156820

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd9fc284e1026'
down_revision: Union[str, Sequence[str], None] = 'de235a2bc4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_legal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre_fantasia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cuit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_cuit'), 'empresas', ['cuit'], unique=True)
    op.create_index(op.f('ix_empresas_nombre_legal'), 'empresas', ['nombre_legal'], unique=True)
    op.create_table('configuracion_empresa',
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('link_google_sheets', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nombre_negocio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color_principal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ruta_logo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ruta_icono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('afip_condicion_iva', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('afip_punto_venta_predeterminado', sa.Integer(), nullable=True),
    sa.Column('direccion_negocio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefono_negocio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mail_negocio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('afip_certificado_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('afip_clave_privada_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id_empresa')
    )
    op.create_table('plantilla_mapeo_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_plantilla', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('mapeo_columnas', sa.JSON(), nullable=True),
    sa.Column('nombre_hoja_excel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fila_inicio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['terceros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_plantilla', 'id_empresa', name='uq_nombre_plantilla_empresa')
    )
    op.create_table('articulo_proveedor',
    sa.Column('id_articulo', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('codigo_articulo_proveedor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_articulo'], ['articulos.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['terceros.id'], ),
    sa.PrimaryKeyConstraint('id_articulo', 'id_proveedor')
    )
    op.create_index(op.f('ix_articulo_proveedor_codigo_articulo_proveedor'), 'articulo_proveedor', ['codigo_articulo_proveedor'], unique=False)
    op.drop_table('plantilla_proveedor')
    op.add_column('articulos', sa.Column('id_empresa', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_articulos_codigo_proveedor'), table_name='articulos')
    op.drop_constraint(op.f('articulos_ibfk_1'), 'articulos', type_='foreignkey')
    op.create_foreign_key(None, 'articulos', 'empresas', ['id_empresa'], ['id'])
    op.drop_column('articulos', 'codigo_proveedor')
    op.drop_column('articulos', 'id_proveedor_principal')
    op.add_column('categorias', sa.Column('id_empresa', sa.Integer(), nullable=False))
    op.drop_index(op.f('nombre'), table_name='categorias')
    op.create_unique_constraint('uq_nombre_empresa_categoria', 'categorias', ['nombre', 'id_empresa'])
    op.create_foreign_key(None, 'categorias', 'empresas', ['id_empresa'], ['id'])
    op.add_column('marcas', sa.Column('id_empresa', sa.Integer(), nullable=False))
    op.drop_index(op.f('nombre'), table_name='marcas')
    op.create_unique_constraint('uq_nombre_empresa_categoria', 'marcas', ['nombre', 'id_empresa'])
    op.create_foreign_key(None, 'marcas', 'empresas', ['id_empresa'], ['id'])
    op.add_column('terceros', sa.Column('id_empresa', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'terceros', 'empresas', ['id_empresa'], ['id'])
    op.add_column('usuarios', sa.Column('id_empresa', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'usuarios', 'empresas', ['id_empresa'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'id_empresa')
    op.drop_constraint(None, 'terceros', type_='foreignkey')
    op.drop_column('terceros', 'id_empresa')
    op.drop_constraint(None, 'marcas', type_='foreignkey')
    op.drop_constraint('uq_nombre_empresa_categoria', 'marcas', type_='unique')
    op.create_index(op.f('nombre'), 'marcas', ['nombre'], unique=True)
    op.drop_column('marcas', 'id_empresa')
    op.drop_constraint(None, 'categorias', type_='foreignkey')
    op.drop_constraint('uq_nombre_empresa_categoria', 'categorias', type_='unique')
    op.create_index(op.f('nombre'), 'categorias', ['nombre'], unique=True)
    op.drop_column('categorias', 'id_empresa')
    op.add_column('articulos', sa.Column('id_proveedor_principal', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('articulos', sa.Column('codigo_proveedor', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'articulos', type_='foreignkey')
    op.create_foreign_key(op.f('articulos_ibfk_1'), 'articulos', 'terceros', ['id_proveedor_principal'], ['id'])
    op.create_index(op.f('ix_articulos_codigo_proveedor'), 'articulos', ['codigo_proveedor'], unique=False)
    op.drop_column('articulos', 'id_empresa')
    op.create_table('plantilla_proveedor',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_proveedor', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre_plantilla', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('mapeo_columnas', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['terceros.id'], name=op.f('plantilla_proveedor_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_articulo_proveedor_codigo_articulo_proveedor'), table_name='articulo_proveedor')
    op.drop_table('articulo_proveedor')
    op.drop_table('plantilla_mapeo_proveedor')
    op.drop_table('configuracion_empresa')
    op.drop_index(op.f('ix_empresas_nombre_legal'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_cuit'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
