"""Sincronizar modelo Articulo y añadir tablas de inventariooooo

Revision ID: de235a2bc4ef
Revises: f12ebba034ac
Create Date: 2025-07-21 00:32:45.799516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de235a2bc4ef'
down_revision: Union[str, Sequence[str], None] = 'f12ebba034ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_terceros_cuit'), 'terceros', ['cuit'], unique=True)
    op.add_column('venta_detalle', sa.Column('descuento_aplicado', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venta_detalle', 'descuento_aplicado')
    op.drop_index(op.f('ix_terceros_cuit'), table_name='terceros')
    # ### end Alembic commands ###
