"""Sincronizar modelo Articulo y añadir tablas de inventario

Revision ID: f12ebba034ac
Revises: 47807780b955
Create Date: 2025-07-21 00:26:39.010431

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f12ebba034ac'
down_revision: Union[str, Sequence[str], None] = '47807780b955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantilla_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('nombre_plantilla', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mapeo_columnas', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['terceros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articulo_codigos',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_articulo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_articulo'], ['articulos.id'], ),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_index(op.f('ix_articulo_codigos_codigo'), 'articulo_codigos', ['codigo'], unique=False)
    op.create_table('articulo_combo',
    sa.Column('id_articulo_padre', sa.Integer(), nullable=False),
    sa.Column('id_articulo_hijo', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_articulo_hijo'], ['articulos.id'], ),
    sa.ForeignKeyConstraint(['id_articulo_padre'], ['articulos.id'], ),
    sa.PrimaryKeyConstraint('id_articulo_padre', 'id_articulo_hijo')
    )
    op.add_column('articulos', sa.Column('codigo_interno', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('articulos', sa.Column('codigo_proveedor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('articulos', sa.Column('unidad_compra', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('articulos', sa.Column('unidad_venta', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('articulos', sa.Column('factor_conversion', sa.Float(), nullable=False))
    op.add_column('articulos', sa.Column('tasa_iva', sa.Float(), nullable=False))
    op.add_column('articulos', sa.Column('margen_ganancia', sa.Float(), nullable=False))
    op.add_column('articulos', sa.Column('auto_actualizar_precio', sa.Boolean(), nullable=False))
    op.add_column('articulos', sa.Column('cantidad_minima_pedido', sa.Float(), nullable=True))
    op.add_column('articulos', sa.Column('cantidad_deseada_pedido', sa.Float(), nullable=True))
    op.add_column('articulos', sa.Column('es_combo', sa.Boolean(), nullable=False))
    op.add_column('articulos', sa.Column('id_proveedor_principal', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_articulos_codigo_barras'), table_name='articulos')
    op.create_index(op.f('ix_articulos_codigo_interno'), 'articulos', ['codigo_interno'], unique=True)
    op.create_index(op.f('ix_articulos_codigo_proveedor'), 'articulos', ['codigo_proveedor'], unique=False)
    op.create_foreign_key(None, 'articulos', 'terceros', ['id_proveedor_principal'], ['id'])
    op.drop_column('articulos', 'codigo_barras')
    op.add_column('compra_detalle', sa.Column('descuento_aplicado', sa.Float(), nullable=False))
    op.create_index(op.f('ix_terceros_cuit'), 'terceros', ['cuit'], unique=True)
    op.add_column('venta_detalle', sa.Column('descuento_aplicado', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venta_detalle', 'descuento_aplicado')
    op.drop_index(op.f('ix_terceros_cuit'), table_name='terceros')
    op.drop_column('compra_detalle', 'descuento_aplicado')
    op.add_column('articulos', sa.Column('codigo_barras', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'articulos', type_='foreignkey')
    op.drop_index(op.f('ix_articulos_codigo_proveedor'), table_name='articulos')
    op.drop_index(op.f('ix_articulos_codigo_interno'), table_name='articulos')
    op.create_index(op.f('ix_articulos_codigo_barras'), 'articulos', ['codigo_barras'], unique=True)
    op.drop_column('articulos', 'id_proveedor_principal')
    op.drop_column('articulos', 'es_combo')
    op.drop_column('articulos', 'cantidad_deseada_pedido')
    op.drop_column('articulos', 'cantidad_minima_pedido')
    op.drop_column('articulos', 'auto_actualizar_precio')
    op.drop_column('articulos', 'margen_ganancia')
    op.drop_column('articulos', 'tasa_iva')
    op.drop_column('articulos', 'factor_conversion')
    op.drop_column('articulos', 'unidad_venta')
    op.drop_column('articulos', 'unidad_compra')
    op.drop_column('articulos', 'codigo_proveedor')
    op.drop_column('articulos', 'codigo_interno')
    op.drop_table('articulo_combo')
    op.drop_index(op.f('ix_articulo_codigos_codigo'), table_name='articulo_codigos')
    op.drop_table('articulo_codigos')
    op.drop_table('plantilla_proveedor')
    # ### end Alembic commands ###
