"""Agregar formato_comprobante a ConfiguracionEmpresa

Revision ID: 66449a312aed
Revises: 728db48bb35f
Create Date: 2025-09-08 14:19:45.575077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '66449a312aed'
down_revision: Union[str, Sequence[str], None] = '728db48bb35f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_usuario_nombre_usuario'), table_name='usuarios')
    #op.drop_table('usuario')
    #op.drop_index(op.f('nombre'), table_name='categoria')
    # op.drop_table('categoria')
    #op.drop_index(op.f('ix_articulo_codigo_barras'), table_name='articulo')
    #op.drop_table('articulo')
    #op.drop_index(op.f('nombre'), table_name='marca')
    #op.drop_table('marca')
    #op.drop_index(op.f('ix_rol_nombre'), table_name='rol')
    #op.drop_table('rol')
    #op.drop_index(op.f('ix_tercero_codigo_interno'), table_name='tercero')
    #op.drop_index(op.f('ix_tercero_identificacion_fiscal'), table_name='tercero')
    #op.drop_index(op.f('ix_tercero_nombre_razon_social'), table_name='tercero')
    #op.drop_table('tercero')
    op.add_column('configuracion_empresa', sa.Column('link_visual_1', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('configuracion_empresa', sa.Column('link_visual_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('configuracion_empresa', sa.Column('link_visual_3', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion_empresa', 'link_visual_3')
    op.drop_column('configuracion_empresa', 'link_visual_2')
    op.drop_column('configuracion_empresa', 'link_visual_1')
    #op.create_table('tercero',
    #sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    #sa.Column('codigo_interno', mysql.VARCHAR(length=255), nullable=True),
    #sa.Column('es_cliente', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    #sa.Column('es_proveedor', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    #sa.Column('nombre_razon_social', mysql.VARCHAR(length=255), nullable=False),
    #sa.Column('nombre_fantasia', mysql.VARCHAR(length=255), nullable=True),
    #sa.Column('identificacion_fiscal', mysql.VARCHAR(length=255), nullable=True),
    #sa.Column('condicion_iva', mysql.VARCHAR(length=255), nullable=False),
    #sa.Column('direccion', mysql.VARCHAR(length=255), nullable=True),
    #sa.Column('localidad', mysql.VARCHAR(length=255), nullable=True),
    #sa.Column('provincia', mysql.VARCHAR(length=255), nullable=True),
    #sa.Column('pais', mysql.VARCHAR(length=255), nullable=True),
    #sa.Column('telefono', mysql.VARCHAR(length=255), nullable=True),
    #sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    #sa.Column('limite_credito', mysql.FLOAT(), nullable=False),
    #sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    #sa.Column('fecha_alta', mysql.DATETIME(), nullable=False),
    #sa.Column('notas', mysql.VARCHAR(length=255), nullable=True),
    #sa.PrimaryKeyConstraint('id'),
    #mysql_collate='utf8mb4_0900_ai_ci',
    #mysql_default_charset='utf8mb4',
    #mysql_engine='InnoDB'
    #)
    #op.create_index(op.f('ix_tercero_nombre_razon_social'), 'tercero', ['nombre_razon_social'], unique=False)
    #op.create_index(op.f('ix_tercero_identificacion_fiscal'), 'tercero', ['identificacion_fiscal'], unique=False)
    #op.create_index(op.f('ix_tercero_codigo_interno'), 'tercero', ['codigo_interno'], unique=False)
    #op.create_table('rol',
    #sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    #sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    #sa.PrimaryKeyConstraint('id'),
    #mysql_collate='utf8mb4_0900_ai_ci',
    #mysql_default_charset='utf8mb4',
    #mysql_engine='InnoDB'
    #)
    #op.create_index(op.f('ix_rol_nombre'), 'rol', ['nombre'], unique=True)
    #op.create_table('marca',
    #sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    #sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    #sa.PrimaryKeyConstraint('id'),
    #mysql_collate='utf8mb4_0900_ai_ci',
    #mysql_default_charset='utf8mb4',
    #mysql_engine='InnoDB'
    #)
    #op.create_index(op.f('nombre'), 'marca', ['nombre'], unique=True)
    #op.create_table('articulo',
    #sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    #sa.Column('codigo_barras', mysql.VARCHAR(length=255), nullable=True),
    #sa.Column('descripcion', mysql.VARCHAR(length=255), nullable=False),
    #sa.Column('precio_costo', mysql.FLOAT(), nullable=False),
    #sa.Column('precio_venta', mysql.FLOAT(), nullable=False),
    #sa.Column('stock_actual', mysql.FLOAT(), nullable=False),
    #sa.Column('stock_minimo', mysql.FLOAT(), nullable=True),
    #sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    #sa.Column('maneja_lotes', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    #sa.Column('id_categoria', mysql.INTEGER(), autoincrement=False, nullable=True),
    #sa.Column('id_marca', mysql.INTEGER(), autoincrement=False, nullable=True),
    #sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id'], name=op.f('articulo_ibfk_1')),
    #sa.ForeignKeyConstraint(['id_marca'], ['marca.id'], name=op.f('articulo_ibfk_2')),
    #sa.PrimaryKeyConstraint('id'),
    #mysql_collate='utf8mb4_0900_ai_ci',
    #mysql_default_charset='utf8mb4',
    #mysql_engine='InnoDB'
    #)
    #op.create_index(op.f('ix_articulo_codigo_barras'), 'articulo', ['codigo_barras'], unique=True)
    #op.create_table('categoria',
    #sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    #sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    #sa.PrimaryKeyConstraint('id'),
    #mysql_collate='utf8mb4_0900_ai_ci',
    #mysql_default_charset='utf8mb4',
    #mysql_engine='InnoDB'
    #)
    #op.create_index(op.f('nombre'), 'categoria', ['nombre'], unique=True)
    #op.create_table('usuario',
    #sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    #sa.Column('nombre_usuario', mysql.VARCHAR(length=255), nullable=False),
    #sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    #sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    #sa.Column('creado_en', mysql.DATETIME(), nullable=False),
    #sa.Column('id_rol', mysql.INTEGER(), autoincrement=False, nullable=False),
    #sa.ForeignKeyConstraint(['id_rol'], ['rol.id'], name=op.f('usuario_ibfk_1')),
    #sa.PrimaryKeyConstraint('id'),
    #mysql_collate='utf8mb4_0900_ai_ci',
    #mysql_default_charset='utf8mb4',
    #mysql_engine='InnoDB'
    #)
    #op.create_index(op.f('ix_usuario_nombre_usuario'), 'usuario', ['nombre_usuario'], unique=True)
    # ### end Alembic commands ###
