"""Crear tabla facturas electronicas

Revision ID: 6a3e5219b777
Revises: 
Create Date: 2025-09-04 15:44:10.543120

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3e5219b777'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturas_electronicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingreso_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cae', sqlmodel.sql.sqltypes.AutoString(length=14), nullable=False),
    sa.Column('numero_comprobante', sa.BigInteger(), nullable=True),
    sa.Column('punto_venta', sa.Integer(), nullable=False),
    sa.Column('tipo_comprobante', sa.Integer(), nullable=False),
    sa.Column('fecha_comprobante', sa.Date(), nullable=True),
    sa.Column('vencimiento_cae', sa.Date(), nullable=True),
    sa.Column('resultado_afip', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.Column('cuit_emisor', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('tipo_doc_receptor', sa.Integer(), nullable=False),
    sa.Column('nro_doc_receptor', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('importe_total', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('importe_neto', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('importe_iva', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cae')
    )
    op.create_index(op.f('ix_facturas_electronicas_fecha_comprobante'), 'facturas_electronicas', ['fecha_comprobante'], unique=False)
    op.create_index(op.f('ix_facturas_electronicas_ingreso_id'), 'facturas_electronicas', ['ingreso_id'], unique=False)
    op.create_index(op.f('ix_facturas_electronicas_nro_doc_receptor'), 'facturas_electronicas', ['nro_doc_receptor'], unique=False)
    op.add_column('configuracion_empresa', sa.Column('aclaraciones_legales', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion_empresa', 'aclaraciones_legales')
    op.drop_index(op.f('ix_facturas_electronicas_nro_doc_receptor'), table_name='facturas_electronicas')
    op.drop_index(op.f('ix_facturas_electronicas_ingreso_id'), table_name='facturas_electronicas')
    op.drop_index(op.f('ix_facturas_electronicas_fecha_comprobante'), table_name='facturas_electronicas')
    op.drop_table('facturas_electronicas')
    # ### end Alembic commands ###
