"""Agregar impreso a consumo detalle

Revision ID: a1b2c3d4e5f6
Revises: 18e0ec242ba9
Create Date: 2026-01-12 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '18e0ec242ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumo_mesa_detalle', sa.Column('impreso', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consumo_mesa_detalle', 'impreso')
    # ### end Alembic commands ###
